name: 'Container spike action'
description: 'A github action container spike'
author: 'Allen Evans'
inputs:
  myInput:
    description: 'Input to use'
    default: 'world'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}
