name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      env:
        TAG: spike-action:$(date +%s)

    - name: Build the Docker image
      run: |
        echo "TAG=$TAG"
        docker build . --file Dockerfile --tag $TAG

    - name: Test
      run: |
        echo "TAG=$TAG"
        docker run $TAG
