name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build the Docker image
      run: |
        export TAG="spike-action:$(date +%s)"
        docker build . --file Dockerfile --tag $TAG

    - name: Test
      run: |
        docker run $TAG
