name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set environment variables
      run: |
        echo "TAG=spike-action:$(date +%s)" > props

    - name: Build the Docker image
      run: |
        export $(cat props | xargs)
        printenv
        docker build . --file Dockerfile --tag $TAG

    - name: Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Test
      run: |
        export $(cat props | xargs)
        printenv
        docker run $TAG
